**nonzero函数**是numpy中用于得到数组array中非零元素的位置（数组索引）的函数。  
它返回的是a.ndim（数组a的轴数）的元组，元组的每个元素都是一个整数数组，其值为非零元素的下标在对应轴上的值。  
（1）只有a中非零元素才会有索引值，那些零值元素没有索引值  
（2）返回的索引值数组是一个2维tuple数组，该tuple数组中包含一维的array数组。其中，一维array向量的个数与a的维数是一致的。  
（3）索引值数组的每一个array均是从一个维度上来描述其索引值。比如，如果a是一个二维数组，则索引值数组有两个array，第一个array从**行维度**来描述索引值；第二个array从**列维度**来描述索引值。  
（4）transpose(np.nonzero(x))函数能够描述出每一个非零元素在不同维度的索引值。  
（5）通过a\[nonzero(a)\]得到所有a中的非零值

In [1]:
import numpy as np

In [2]:
# a是一个一维数组
a = [0,2,3]

In [3]:
b = np.nonzero(a)

In [4]:
b

(array([1, 2], dtype=int64),)

In [5]:
np.array(b).ndim

2

In [6]:
# a 是一个二维数组
a = np.array([[0,0,3],[0,0,0],[0,0,9]])

In [7]:
b = np.nonzero(a)

In [8]:
b

(array([0, 2], dtype=int64), array([2, 2], dtype=int64))

In [9]:
np.array(b).ndim

2

In [10]:
np.transpose(np.nonzero(a))

array([[0, 2],
       [2, 2]], dtype=int64)

（1）a中有2个非零元素，因此，索引值tuple中array的长度为2。因为，只有非零元素才有索引值。

（2）索引值数组是2 维的。实际上，无论a的维度是多少，索引值数组一定是2维的tuple，但是tuple中的一维array个数和a的维数一致。

（3）第1个array(\[0, 2\])是从row值上对3和9进行的描述。第2个array(\[2, 2\])是从col值上对3和9的描述。这样，从行和列上两个维度上各用一个数组来描述非零索引值。

（4）通过调用np.transpose()函数，得出3的索引值是\[0 2\]，即第0行，第2列。

In [11]:
b2 = np.array([[True,False,True],[True,False,False]])

In [12]:
np.nonzero(b2)

(array([0, 0, 1], dtype=int64), array([0, 2, 0], dtype=int64))

In [13]:
a = np.arange(3*4*5).reshape(3,4,5)

In [14]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [15]:
b2

array([[ True, False,  True],
       [ True, False, False]])

In [16]:
a[np.nonzero(b2)]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [17]:
# a是三维数组
a = np.array([[[0,0],[1,0]],[[0,0],[1,0]],[[0,0],[1,0]]])

In [18]:
a

array([[[0, 0],
        [1, 0]],

       [[0, 0],
        [1, 0]],

       [[0, 0],
        [1, 0]]])

In [19]:
b = np.nonzero(a)

In [20]:
b

(array([0, 1, 2], dtype=int64),
 array([1, 1, 1], dtype=int64),
 array([0, 0, 0], dtype=int64))

In [21]:
np.array(b).ndim

2

机器学习实战中的代码（对numpy.nonzero的应用）

In [22]:
import numpy as np

In [23]:
def binSplitDataSet(dataSet,feature,value):
    mat0 = dataSet[np.nonzero(dataSet[:,feature]>value)[0],:]
    mat1 = dataSet[np.nonzero(dataSet[:,feature]<=value)[0],:]
    return mat0,mat1

In [24]:
testMat = np.mat(np.eye(4))

In [25]:
testMat

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [26]:
testMat[:,1]

matrix([[0.],
        [1.],
        [0.],
        [0.]])

In [27]:
testMat[:,1]>0.5

matrix([[False],
        [ True],
        [False],
        [False]])

In [28]:
np.nonzero(testMat[:,1]>0.5)

(array([1], dtype=int64), array([0], dtype=int64))

In [29]:
np.nonzero(testMat[:,1]>0.5)[0]

array([1], dtype=int64)

In [30]:
testMat[np.nonzero(testMat[:,1]>0.5)[0],:]

matrix([[0., 1., 0., 0.]])

In [31]:
testMat[np.nonzero(testMat[:,1]>0.5)[0],:][0]

matrix([[0., 1., 0., 0.]])

In [32]:
testMat[np.nonzero(testMat[:,1]<=0.5)[0],:]

matrix([[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [33]:
testMat[np.nonzero(testMat[:,1]<=0.5)[0],:][0]

matrix([[1., 0., 0., 0.]])

In [34]:
mat0,mat1 = binSplitDataSet(testMat,1,0.5)

In [35]:
mat0

matrix([[0., 1., 0., 0.]])

In [36]:
mat1

matrix([[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

再一个验证的例子

In [37]:
testMat = np.mat(np.eye(4))

In [38]:
testMat

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [39]:
np.nonzero(testMat>0.5) # 对于大于0.5的元素的横纵坐标的描述

(array([0, 1, 2, 3], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [40]:
np.transpose(np.nonzero(testMat>0.5)) # 元素坐标

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]], dtype=int64)

In [41]:
testMat[:,1]

matrix([[0.],
        [1.],
        [0.],
        [0.]])

In [42]:
a = np.transpose(np.nonzero(testMat>0.5))

In [43]:
a

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]], dtype=int64)

In [44]:
testMat[:,1]

matrix([[0.],
        [1.],
        [0.],
        [0.]])

In [45]:
a = np.transpose(np.nonzero(testMat[:,1]>0.5))

In [46]:
a

array([[1, 0]], dtype=int64)

In [47]:
a[0] # 因为a[0]是[1,0]

array([1, 0], dtype=int64)

In [48]:
testMat[a[0],:] # 得到了testMat的第二行和第一行

matrix([[0., 1., 0., 0.],
        [1., 0., 0., 0.]])

In [49]:
testMat[a[0],:][0] # 得到了针对testMat第1列元素中大于0.5的元素所在行

matrix([[0., 1., 0., 0.]])