In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [5]:
np.tile(a,(1,4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [6]:
np.tile(a,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [7]:
np.tile(a,(2,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])