In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
obj = pd.Series([4,7,-5,8])

In [4]:
obj

0    4
1    7
2   -5
3    8
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  8], dtype=int64)

In [6]:
obj.index #和range(4)

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj = pd.Series([4,7,-5,3],index=['b','d','a','c'])

In [8]:
obj

b    4
d    7
a   -5
c    3
dtype: int64

In [9]:
obj.index

Index(['b', 'd', 'a', 'c'], dtype='object')

In [10]:
obj['a']

-5

In [11]:
obj[obj>0]

b    4
d    7
c    3
dtype: int64

In [12]:
obj*2

b     8
d    14
a   -10
c     6
dtype: int64

In [13]:
np.exp(obj)

b      54.598150
d    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [14]:
'b' in obj

True

In [15]:
'e' in obj

False

In [16]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [17]:
obj = pd.Series(sdata)

In [18]:
obj

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [20]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [21]:
frame.head() #head方法会选取前五行

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [22]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [23]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

In [24]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [25]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [26]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [27]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [28]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [29]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object

In [30]:
frame2['debt'] = 16.5

In [31]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [32]:
frame2['debt'] = np.arange(6.)

In [33]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

将列表或者数组的值赋值给某一列时，其长度**必须**与DataFrame的长度相匹配。  
如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有空位都将被填上缺失值  

In [34]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [35]:
frame2['debt'] = val

In [36]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [37]:
frame2['eastern'] = frame2.state == 'Ohio'

注意不能使用frame2.eastern创建新的列

In [38]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [39]:
del frame2['eastern']

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

另一种常见的数据形式是嵌套字典

In [41]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [42]:
frame3 = pd.DataFrame(pop)

In [43]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [44]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [45]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [46]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}

In [47]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [48]:
frame3.index.name = 'year'

In [49]:
frame3.columns.name = 'state'

In [50]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [51]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [52]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [53]:
obj = pd.Series(range(3),index=['a','b','c'])

In [54]:
index = obj.index

In [55]:
index

Index(['a', 'b', 'c'], dtype='object')

In [56]:
index[1:]

Index(['b', 'c'], dtype='object')

In [57]:
# index[1] = 'd'
# index对象是不可变的，因此用户不能对其进行修改

In [58]:
labels = pd.Index(np.arange(3))

In [59]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [60]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [61]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [62]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [63]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [64]:
'Ohio' in frame3.columns

True

In [65]:
2003 in frame3.index

False

In [66]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [67]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [68]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [69]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [70]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [71]:
obj3

0      blue
2    purple
4    yellow
dtype: object

对于时间序列这样的有序数据，重新索引时可能需要一些插值处理  
method选项可以达到此目的，例如，ffill可以实现向前值填充

In [72]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [73]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns = ['Ohio','Texas','California'])

In [74]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [75]:
frame2 = frame.reindex(['a','b','c','d'])

In [76]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [77]:
states = ['Texas','Utha','California']

In [78]:
frame.reindex(columns=states)

Texas  Utha  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

丢弃掉某条轴上的一个或多个项只要有一个索引数组或列表即可。

In [79]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [80]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [81]:
new_obj = obj.drop('c')

In [82]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [83]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

对于DataFrame，可以删除任意轴上的索引值。

In [84]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utha','New York'],
                   columns=['one','two','three','four'])

In [85]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

用标签序列调用drop会从行标签(axis=0)删除值

In [86]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utha        8    9     10    11
New York   12   13     14    15

In [87]:
#data.drop('two',axis='columns')
data.drop('two',axis=1) #1表示列，0表示行

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utha        8     10    11
New York   12     14    15

In [88]:
li = data['four'].astype(np.float64)

In [89]:
li

Ohio         3.0
Colorado     7.0
Utha        11.0
New York    15.0
Name: four, dtype: float64

索引、选取、过滤  
Series索引的工作方式类似于NumpPy数组的索引，只不过Series的索引值不只是整数

In [90]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])

In [91]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [92]:
for i in range(len(obj)):
    print(obj[i],end=',')

0.0,1.0,2.0,3.0,

In [93]:
obj['b']

1.0

In [94]:
obj[1]

1.0

In [95]:
obj[2:4] #[2,4)

c    2.0
d    3.0
dtype: float64

In [96]:
#  这样的书写格式会报错 obj['b','a','d']
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [97]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [98]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

**利用标签的切片运算与普通的Python切片运算不同，其末端是包含的**

In [99]:
obj['a':'b']

a    0.0
b    1.0
dtype: float64

In [100]:
obj['a':'b'].values

array([0., 1.])

In [101]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [102]:
obj['b':'c']=5

In [103]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

用一个值或者序列对DataFrame进行索引，其实就是获取一个或多个列

In [104]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])

In [105]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [106]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [107]:
data[['two','three']]

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [108]:
data[:2] #前两行

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [109]:
data[data['three']>5] #返回的是data['three']＞5的那些行

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [111]:
data[data<5] = 0

In [112]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

用loc和iloc进行选取  
loc  轴标签  
iloc 整数索引

In [113]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [114]:
data.iloc[2,[3,0,1]] #第三行的第四列，第一列，第二列

four    11
one      8
two      9
Name: Utah, dtype: int32

In [115]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [116]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [117]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [119]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [120]:
data.loc['Utah']

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [121]:
ser = pd.Series(np.arange(3.))

In [122]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [123]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [124]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [125]:
ser2[-1]

2.0

In [126]:
#ser[-1] 因为会产生歧义
ser.iloc[-1]

2.0

In [127]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [128]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index = ['a','c','e','f','g'])

In [129]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [130]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [131]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

对于DataFrame,对齐操作会同时发生在行和列上

In [132]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                  index=['Ohio','Texas','Colorado'])

In [133]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                   index=['Utah','Ohio','Texas','Oregon'])

In [134]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [135]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [136]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [137]:
df1 = pd.DataFrame({'A':[1,2]})

In [138]:
df2 = pd.DataFrame({'B':[3,4]})

In [139]:
df1

A
0  1
1  2

In [140]:
df2

B
0  3
1  4

In [141]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [142]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns = list('abcd'))

In [143]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns=list('abcde'))

In [144]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [145]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [146]:
df2.loc[1,'b'] = np.nan

In [147]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

当他们相加的时候没有重叠的地方就会产生NA值

In [148]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

**神奇的add方法和fill_value**

In [149]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [150]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [151]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [152]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [153]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [154]:
arr = np.arange(12.).reshape((3,4))

In [155]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [156]:
arr[0]

array([0., 1., 2., 3.])

In [157]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [158]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])

In [159]:
series = frame.iloc[0]

In [160]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [161]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [162]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [163]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [164]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [165]:
series3 = frame['d']

In [166]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [167]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [168]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

函数的应用和映射

In [169]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])

In [170]:
frame

b         d         e
Utah   -0.481253 -0.779381 -0.911059
Ohio    1.216132 -0.172998  0.367660
Texas  -1.655680 -0.247816  0.644506
Oregon -0.444922  0.834807 -1.346118

In [171]:
np.abs(frame)

b         d         e
Utah    0.481253  0.779381  0.911059
Ohio    1.216132  0.172998  0.367660
Texas   1.655680  0.247816  0.644506
Oregon  0.444922  0.834807  1.346118

In [172]:
f = lambda x:x.max()-x.min()

In [173]:
frame.apply(f) #每列都执行一次

b    2.871812
d    1.614188
e    1.990624
dtype: float64

In [174]:
frame.apply(f,axis=1)

Utah      0.429806
Ohio      1.389130
Texas     2.300186
Oregon    2.180925
dtype: float64

In [175]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [176]:
frame.apply(f)

b         d         e
min -1.655680 -0.779381 -1.346118
max  1.216132  0.834807  0.644506

排序和排名

In [177]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [178]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

对于DataFrame,可以根据任意一个轴上的索引进行排序

In [179]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])

In [180]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [181]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [182]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

默认是按照升序排列的，也可以按照降序排序

In [183]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [184]:
obj = pd.Series([4,7,-3,2])

In [185]:
l = obj.sort_values()

In [186]:
l

2   -3
3    2
0    4
1    7
dtype: int64

In [187]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [188]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [189]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [190]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [191]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [192]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [193]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [194]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])

In [195]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [196]:
obj.index.is_unique

False

In [197]:
obj['a']

a    0
a    1
dtype: int64

In [198]:
obj['c']

4

In [199]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [200]:
df

0         1         2
a -0.159898  0.111510 -1.256917
a -0.495954 -0.487200 -1.354328
b -1.408670  0.312854  0.150864
b -0.150234  0.539271  0.701195

In [201]:
df.loc['a']

0        1         2
a -0.159898  0.11151 -1.256917
a -0.495954 -0.48720 -1.354328

In [202]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [203]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

NAN会被自动排除，除非整个切片都是NA。

In [204]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [205]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [206]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [207]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [208]:
obj = pd.Series(['a','a','b','c']*4)

In [209]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [210]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [211]:
obj.sum()

'aabcaabcaabcaabc'