In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.20504443,  0.56353872,  1.40646844],
       [ 0.53031847, -1.38880066, -0.82918587]])

In [4]:
data*10

array([[ -2.0504443 ,   5.63538715,  14.06468439],
       [  5.30318467, -13.8880066 ,  -8.29185875]])

In [5]:
data + data

array([[-0.41008886,  1.12707743,  2.81293688],
       [ 1.06063693, -2.77760132, -1.65837175]])

In [6]:
data.shape#一个表示各维度大小的元组

(2, 3)

In [7]:
data.dtype #一个用于说明数组数据类型的对象

dtype('float64')

创建ndarray

In [8]:
data = [1,2,3,4,5]
data = np.array(data)
data

array([1, 2, 3, 4, 5])

In [9]:
data = [[1,2,3],[4,5,6]]
data = np.array(data)
print(data)
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

empty可以创建一个没有任何具体数值的数组

In [12]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

full和zeros和ones类似

In [14]:
np.full((2,3),1)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
np.eye(3) #单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [17]:
data = np.array([1,2,3],dtype=np.float64)

In [18]:
data

array([1., 2., 3.])

In [19]:
data = np.array([1,2,3],dtype=np.int64)

In [20]:
data

array([1, 2, 3], dtype=int64)

可以通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype,在下面地例子中是整数被转换成了浮点数。

In [21]:
data = np.array([1,2,3,4,5])

In [22]:
data.dtype

dtype('int32')

In [23]:
float_arr = data.astype(np.float64)

In [24]:
float_arr.dtype

dtype('float64')

In [25]:
float_arr

array([1., 2., 3., 4., 5.])

如果将浮点数转换成整数，则小数部分则会被截取删除

In [26]:
data = np.array([3.4,2.4,1.5,9.9])

In [27]:
data

array([3.4, 2.4, 1.5, 9.9])

In [28]:
data.astype(np.int32)

array([3, 2, 1, 9])

使用numpy。string_类型时，一定要小心，因为Numpy的字符串数据是大小固定的，发生截取时，不会发出警报。

In [29]:
data = np.array(['1.23','1.255','-93.3'],dtype=np.string_)

In [30]:
data.astype(np.float64) #np.float 或者 float都可以

array([  1.23 ,   1.255, -93.3  ])

Numpy数组的运算

In [31]:
data = np.array([[1.,2.,3.],[4.,5.,6.]])

In [32]:
data

array([[1., 2., 3.],
       [4., 5., 6.]])

大小相等的数组之间的任何算术运算都会将运算应用到元素级

In [33]:
data * data

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [34]:
data - data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
1 / data

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [36]:
data ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
data1 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [38]:
data1

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
data1 > data

array([[False,  True, False],
       [ True, False,  True]])

In [40]:
data = np.arange(10)

In [41]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
data[5]

5

In [43]:
data[5:8]

array([5, 6, 7])

In [44]:
data[5:8] = 12

In [45]:
data

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [46]:
data1 = data[5:8]

In [47]:
data1

array([12, 12, 12])

In [48]:
data1[1] = 12345 #修改了data1中的值，data中的值也会改变

In [49]:
data

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

二维数组的切片方式稍显不同

In [50]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [51]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
data[:2]#选取前两行

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
data[1,1:]

array([5, 6])

In [54]:
data[:,:1]

array([[1],
       [4],
       [7]])

In [55]:
name = np.array(['Bob','Joe','Will','will','bob','joe','Joe'])

In [56]:
data = np.random.randn(7,4)

In [57]:
name

array(['Bob', 'Joe', 'Will', 'will', 'bob', 'joe', 'Joe'], dtype='<U4')

In [58]:
data

array([[ 1.07545896, -1.40738466, -1.65476903,  1.14453615],
       [-0.03595277,  0.33246961, -0.47760026,  1.32465997],
       [-1.16754247,  0.77136622, -0.94623857, -0.05699739],
       [ 0.13667125,  0.56066601, -0.95081612, -1.12071501],
       [ 0.7567293 , -0.36657156,  1.09980215, -0.83496296],
       [ 0.39965505,  0.02658074, -1.03607805,  0.91481752],
       [-0.25403658,  0.01055174, -0.29712452, -0.05657004]])

In [59]:
name == 'Bob'

array([ True, False, False, False, False, False, False])

因为在name里，只有index=0的时候，才是Bob，返回的就是data中index是0的那一行

In [60]:
data[name=='Bob'] 

array([[ 1.07545896, -1.40738466, -1.65476903,  1.14453615]])

In [61]:
data[name=='Bob',2:]

array([[-1.65476903,  1.14453615]])

~表示取反

In [62]:
data[~(name=='Bob')] 

array([[-0.03595277,  0.33246961, -0.47760026,  1.32465997],
       [-1.16754247,  0.77136622, -0.94623857, -0.05699739],
       [ 0.13667125,  0.56066601, -0.95081612, -1.12071501],
       [ 0.7567293 , -0.36657156,  1.09980215, -0.83496296],
       [ 0.39965505,  0.02658074, -1.03607805,  0.91481752],
       [-0.25403658,  0.01055174, -0.29712452, -0.05657004]])

In [63]:
data

array([[ 1.07545896, -1.40738466, -1.65476903,  1.14453615],
       [-0.03595277,  0.33246961, -0.47760026,  1.32465997],
       [-1.16754247,  0.77136622, -0.94623857, -0.05699739],
       [ 0.13667125,  0.56066601, -0.95081612, -1.12071501],
       [ 0.7567293 , -0.36657156,  1.09980215, -0.83496296],
       [ 0.39965505,  0.02658074, -1.03607805,  0.91481752],
       [-0.25403658,  0.01055174, -0.29712452, -0.05657004]])

In [64]:
data[data<0]=0 #将data中所有负数设为0

In [65]:
data

array([[1.07545896, 0.        , 0.        , 1.14453615],
       [0.        , 0.33246961, 0.        , 1.32465997],
       [0.        , 0.77136622, 0.        , 0.        ],
       [0.13667125, 0.56066601, 0.        , 0.        ],
       [0.7567293 , 0.        , 1.09980215, 0.        ],
       [0.39965505, 0.02658074, 0.        , 0.91481752],
       [0.        , 0.01055174, 0.        , 0.        ]])

In [66]:
data[data==0]=7.9

In [67]:
data

array([[1.07545896, 7.9       , 7.9       , 1.14453615],
       [7.9       , 0.33246961, 7.9       , 1.32465997],
       [7.9       , 0.77136622, 7.9       , 7.9       ],
       [0.13667125, 0.56066601, 7.9       , 7.9       ],
       [0.7567293 , 7.9       , 1.09980215, 7.9       ],
       [0.39965505, 0.02658074, 7.9       , 0.91481752],
       [7.9       , 0.01055174, 7.9       , 7.9       ]])

数组转置和轴对换

In [68]:
data = np.arange(15).reshape((3,5))

In [69]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
data.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [71]:
data = np.arange(10)

In [72]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.sqrt(data)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
np.exp(data)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [75]:
x = np.random.randn(8)

In [76]:
x

array([-1.19075426, -0.45921144, -0.0652461 , -1.71578498, -0.14993841,
        0.44728593,  0.86282594,  0.35447197])

In [77]:
y = np.random.randn(8)

In [78]:
y

array([ 0.07010304, -0.18508403,  1.02059839,  0.54315659,  0.49737093,
       -0.34785358, -0.47772942,  1.00462104])

In [79]:
np.maximum(x,y)

array([ 0.07010304, -0.18508403,  1.02059839,  0.54315659,  0.49737093,
        0.44728593,  0.86282594,  1.00462104])

In [80]:
points = np.arange(-5,5,0.01)

In [81]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [82]:
xs,ys = np.meshgrid(points,points)

In [83]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [84]:
z = np.sqrt(xs**2+ys**2)

In [85]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [86]:
x = np.array([1.1,1.2,1.3,1.4,1.5])

In [87]:
y = np.array([2.1,2.2,2.3,2.4,2.5])

In [88]:
cond = np.array([True,False,True,True,False])

In [89]:
result = [(xx if c  else yy) for xx,yy,c in zip(x,y,cond)]

In [90]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [91]:
result = np.where(cond,x,y)

In [92]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

np.where的第二个和第三个参数不必是数组，它们可以是标量值  
在数据分析工作时，where通常用于根据另一个数组而产生一个新的数组。

In [93]:
data = np.random.randn(4,4)

In [94]:
data

array([[ 0.4531729 ,  2.20616399,  0.31971312,  1.14683817],
       [ 0.26775856,  0.28403911, -0.05834117,  1.44237114],
       [-0.13398649,  0.56853033, -1.07207612, -0.69848644],
       [-0.53901769,  1.60675046, -0.38361578, -0.4806071 ]])

In [95]:
data > 0

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [False,  True, False, False]])

In [96]:
np.where(data>0,2,-1)

array([[ 2,  2,  2,  2],
       [ 2,  2, -1,  2],
       [-1,  2, -1, -1],
       [-1,  2, -1, -1]])

In [97]:
np.where(data>0,2,data)

array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        , -0.05834117,  2.        ],
       [-0.13398649,  2.        , -1.07207612, -0.69848644],
       [-0.53901769,  2.        , -0.38361578, -0.4806071 ]])

np.unique 它用于找出数组中唯一值并返回已排序的结果

In [98]:
name = np.array(['Bob','Bob',"joe","Joe","Joe"])

In [99]:
np.unique(name)

array(['Bob', 'Joe', 'joe'], dtype='<U3')

线性代数  
矩阵乘法

In [100]:
x = np.array([[1,2,3],[4,5,6]])

In [101]:
y = np.array([[6,23],[-1,7],[8,9]])

In [102]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [104]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])