In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1,10,size = 5)


In [4]:
values = np.random.randint(1,10,size=5)

In [5]:
values

array([4, 6, 3, 5, 8])

In [6]:
compute_reciprocals(values)

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [7]:
big_array = np.random.randint(1,100,size=1000000)

In [8]:
big_array

array([71, 89, 89, ..., 82, 58, 71])

In [9]:
%timeit compute_reciprocals(big_array)

3.54 s ± 203 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
print(compute_reciprocals(values))
print(1.0/values)

[0.25       0.16666667 0.33333333 0.2        0.125     ]
[0.25       0.16666667 0.33333333 0.2        0.125     ]


In [11]:
%timeit (1.0/big_array)

8.06 ms ± 695 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 1.通用函数介绍
NumPy为很多类型的操作提供了方便的接口、静态类型的、可编译程序的接口，也被称作**向量**操作。通过简单的对数组的执行操作来实现，这里对数组的操作将会被用于数组中的每一个元素。这种向量方法被用于将循环推送至NumPy之下的编译层，这样会取得更快的执行效率。<br>
NumPy中的向量操作是用**通用向量**实现的，通用函数主要目的是对NumPy数组中的值执行更快的重复操作。<br>
可以对标量数组进行运算，也可以对两个数组进行运算

In [12]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

不仅限于一维数组的运算，也可以进行多维数组的运算

In [13]:
x = np.arange(9).reshape((3,3))

In [14]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
2 ** x #每一个元素都进行幂指函数的运算

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

# 探索NumPy的通用函数
通用函数两种存在形式：一元通用函数，二元通用函数
## 1.数组的运算
他用了Python中原生的算术运算符，标准的加减乘除都可以使用

In [16]:
x = np.arange(4)
print("x = ",x)
print("x + 5 = ",x + 5)
print("x - 5 = ",x - 5)
print("x * 2 = ",x * 2)
print("x / 2 = ",x / 2)
print("x // 2 = ",x // 2)

x =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


还有求负数，\*\*表示指数运算符，%表示模运算符的一元通用函数<br>
还可以将这些算数运算符组合使用

In [17]:
print("-x = ",-x)
print("x ** 2 = ",x ** 2)
print("x % 2 = ",x%2)
print(-(x*0.5+1)**2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
[-1.   -2.25 -4.   -6.25]


这些算数运算符都是NumPy内置函数的简单封装器

### NumPy实现的算术运算符
运算符 | 对应的通用函数 | 描述
-|-|-
+ | np.add | 加法运算
- | np.subtract | 减法运算
- | np.negative | 负数运算
* | np.multiply | 乘法运算
/ | np.divide | 除法运算
// | np.floor_divide | 地板除法运算（3//2=1）
** | np.power | 指数运算
% | np.mod | 模/余数

In [18]:
np.add(x,2)

array([2, 3, 4, 5])

## 2.绝对值
正如NumPy能理解Python内置的运算操作，NumPy也可以理解Python内置的绝对值函数:<br>
对应的NumPy通用函数是**np.absolute**，该函数也可以用别名np.abs来访问

In [19]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [20]:
np.absolute(x) #与之对应的通用函数

array([2, 1, 0, 1, 2])

In [21]:
np.abs(x)

array([2, 1, 0, 1, 2])

这个通用函数也可以处理**复数**。当处理复数时，绝对值返回的是该复数的模

In [22]:
x = np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

## 3.三角函数
先定义一个角度数组：

In [23]:
theta = np.linspace(0,np.pi,3)

In [24]:
print("theta = ",theta)
print("sin(theta) = ",np.sin(theta))
print("cos(theta) = ",np.cos(theta))
print("tan(theta) = ",np.tan(theta))
#这些值都是在机器精度内计算的，所以有些应该是0的值并没有精确到0

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


逆三角函数同样可以使用：

In [25]:
x = [-1,0,1]
print("x = ",x)
print("arcsin(x) = ",np.arcsin(x))
print("arccos(x) = ",np.arccos(x))
print("arctan(x) = ",np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## 4.指数和对数

In [26]:
x = [1,2,3]
print("x = ",x)
print("e^x = ",np.exp(x))
print("2^x = ",np.exp2(x))
print("3^x = ",np.power(3,x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


指数运算的逆运算，即对数运算也是有用的。最基本的np.log给出的是以自然常数(e)为底数的对数。

In [27]:
x = [1,2,4,10]
print("x = ",x)
print("ln(x) = ",np.log(x))
print("log2(x) = ",np.log2(x))
print("log10(x) = ",np.log10(x))

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


对于非常小的输入值可以保持比较好的精度：

In [28]:
x = [0,0.001,0.01,0.1]
print("exp(x) = ",np.expm1(x))
print("log(1+x) = ",np.log1p(x))

exp(x) =  [0.         0.0010005  0.01005017 0.10517092]
log(1+x) =  [0.         0.0009995  0.00995033 0.09531018]


# 高级的通用函数特性
## 1.指定输出
在进行大量运算时，有时候指定一个用于存放运算结果的数组是非常有用的。不同于创建临时数组，你可以用这个特性将计算结果直接写入到你期望的存储位置。所有的通用函数都可以通过out参数来指定计算结果存放的位置。

In [29]:
x = np.arange(5)
print(x)
y = np.empty(5)
np.multiply(x,10,out=y)

[0 1 2 3 4]


array([ 0., 10., 20., 30., 40.])

这个特性也可以被用作数组视图

In [30]:
y = np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


以下的结果将会创建一个临时数组，该数组存放的是2\*\*x的结果，并且接下来会将这些值复制到y数组中。对于上述例子比较小的计算量来说，这两种方式的差别并不大，但是对于比较大的数组，通过慎重使用out参数能够有效节约内存。

In [31]:
y[::2] = 2 ** x

In [32]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

## 2.聚合
二元通用函数的聚合功能，这些聚合可以直接在对象上计算。例如，我们希望用一个特定的运算reduce一个数组，那么可以用任何通用函数的reduce方法。<br>
一个reduce方法会对给定的元素和操作重复执行，直至得到单个的结果。

In [33]:
x = np.arange(1,6)
np.add.reduce(x) #返回数组中所有元素的和

15

In [34]:
np.multiply.reduce(x) #返回数组中所有元素的乘积

120

如果需要计算每次计算的中间结果，可以使用accumulate

In [35]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [36]:
print(np.multiply.accumulate(x))

[  1   2   6  24 120]


## 3.外积
任何函数可以用outer方法获得两个不同输入数组所有元素对的函数运算结果。

In [37]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [38]:
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

通用函数另外一个非常有用的特性就是可以操作不同大小的数组，一组这样的操被称为**广播**