用于Python科学计算与可视化的扩展模块主要有：<br>NumPy,SciPy,SymPy,matplotlib,Traits,TraitsUI,Chaco,TVTK,Mayavi,VPython,OpenCV

## numpy
科学计算包，支持N维数组运算、处理大型矩阵、成熟的广播库函数、矢量运算、线性代数、傅里叶变换、随机数生成，并可与C++/Fortran语言无缝结合。
## scipy
scipy依赖于numpy，提供了更多的数学工具，包括矩阵运算、线性方程组求解、积分、优化等等。
## matplotlib 
依赖于numpy模块和tkinter模块，可以绘制多种形式的图形，包括线图、直方图、饼状图、散点图、误差线图等等。

In [1]:
import numpy as np

## 1.生成数组
- np.array()
- np.linspace() 生成等差数组
- np.logspace()
- np.zeros()
- np.ones()
- np.identity()  单位矩阵
- np.empty() 空数组，只申请空间而不初始化，元素值是不确定的

In [2]:
np.array((1,2,3,4,5)) #把Python列表转换为数组

array([1, 2, 3, 4, 5])

In [3]:
np.array(range(5)) #把Python的range对象转换成数组

array([0, 1, 2, 3, 4])

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.linspace(0,10,11) # 生成等差数组

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [7]:
#表示的是10的幂
np.logspace(0,100,10) #对数数组

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

In [8]:
np.logspace(0,9,10)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09])

In [9]:
np.zeros((3,3)) #全0二维数组

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((3,1)) #全0一维数组

array([[0.],
       [0.],
       [0.]])

In [11]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [12]:
np.ones((3,3)) #全1二维数组

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((1,3)) #全1一维数组

array([[1., 1., 1.]])

In [14]:
np.identity(3) #单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.empty((3,3)) #空数组，只申请空间而不初始化，元素值是不确定的

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 2.数组与数值的算术运算
- 数组与数值相乘，所有元素与数值相乘
- 数组与数值相除
- 数组与数值整除
- 幂运算
- 数组与数值相加
- 余数

In [16]:
x = np.array((1,2,3,4,5))

In [17]:
x

array([1, 2, 3, 4, 5])

In [18]:
x * 2 #数组与数值相乘，所有元素与数值相乘

array([ 2,  4,  6,  8, 10])

In [19]:
x / 2 #数组与数值相除

array([0.5, 1. , 1.5, 2. , 2.5])

In [20]:
x // 2 #数组与数整除

array([0, 1, 1, 2, 2], dtype=int32)

In [21]:
x ** 3 #幂运算

array([  1,   8,  27,  64, 125], dtype=int32)

In [22]:
x + 2 #数组与数值相加

array([3, 4, 5, 6, 7])

In [23]:
x % 3 #余数

array([1, 2, 0, 1, 2], dtype=int32)

## 3.数组与数组的运算
- 数组之间的加法运算
- 数组之间的减法运算
- 数组之间的乘法运算
- 数组之间的除法运算

In [24]:
# 相乘的条件 a的列数等于b的行数
a = np.array((1,2,3))
b = np.array(([1,2,3],[4,5,6],[7,8,9]))
c = a * b

In [25]:
c #数组与数组相乘，a中的每一个元素乘以b中的每一列元素

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [26]:
c / b #数组之间的除法运算

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [27]:
c / a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [28]:
a + a #数组之间的加减乘除

array([2, 4, 6])

In [29]:
a * a #数组之间的乘法运算

array([1, 4, 9])

In [30]:
a - a #数组之间的减法运算

array([0, 0, 0])

In [31]:
a / a #数组之间的除法运算

array([1., 1., 1.])

## 4.转置

In [32]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
b.T #转置

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
a = np.array((1,2,3,4))

In [36]:
a

array([1, 2, 3, 4])

In [37]:
a.T #一维数组转置以后和原来是一样的

array([1, 2, 3, 4])

## 5.向量内积

In [38]:
a = np.array((5,6,7))

In [39]:
b = np.array((6,6,6))

In [40]:
a.dot(b) #向量内积

108

In [41]:
c = np.array(([1,2,3],[4,5,6],[7,8,9])) #二维数组

In [42]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
cT = c.T #转置

In [44]:
cT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
a

array([5, 6, 7])

In [46]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 需要注意a.dot(c)  和 c.dot(a)
这里c是二维矩阵，a是一维向量，
如果是c.dot(a)，则二维数组的每一行与一维向量计算内积
如果a.dot(c),则一维向量与二维向量的每列计算内积

In [47]:
c.dot(a) #二维数组的每一行与一维向量进行内积，例如第一行是5+12+21

array([ 38,  92, 146])

In [48]:
c[0].dot(a) #5+12+17

38

In [49]:
c[1].dot(a) #20+30+42

92

In [50]:
c[2].dot(a) #35+48+63

146

In [51]:
a.dot(c) #一维向量与二维向量的每列计算内积  
#第一个元素就是5+24+49

array([ 78,  96, 114])

In [52]:
a.dot(cT[0])

78

In [53]:
a.dot(cT[1])

96

In [54]:
a.dot(cT[2])

114

## 6.数组元素访问

In [55]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [56]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
b[0]

array([1, 2, 3])

In [58]:
b[0][0]

1

#### 数组多元素同时访问

In [59]:
x = np.arange(0,100,10,dtype = np.float)

In [60]:
x

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [61]:
x[[1,3,5]]

array([10., 30., 50.])

In [62]:
index = np.random.randint(0,len(x),5) #随机生成5个整数作为下标

In [63]:
index

array([2, 9, 9, 8, 4])

In [64]:
x[index] #同时访问多个元素的值

array([20., 90., 90., 80., 40.])

In [65]:
x

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

numpy.random.standard_normal(size=None)：生产一个浮点数或N维浮点数组，**取数范围：标准正态分布随机样本**

In [66]:
noise = np.random.standard_normal(5)*0.3  #随机噪声

In [67]:
noise

array([-0.07903175, -0.10801327, -0.07770374,  0.36009378, -0.00727043])

In [68]:
x[index] += noise #添加噪声

In [69]:
x[index]

array([19.92096825, 89.92229626, 89.92229626, 80.36009378, 39.99272957])

## 7.对数组进行函数运算

In [70]:
x = np.arange(0,100,10,dtype=np.floating)

In [71]:
x

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [72]:
np.sin(x) #一维数组中所有元素求正弦值

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316,
       -0.26237485, -0.30481062,  0.77389068, -0.99388865,  0.89399666])

In [73]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [74]:
np.cos(b) #二维数组中所有元素求余弦值

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [75]:
np.round(_) #四舍五入，和强制类型转换是不一样的

array([[ 1., -0., -1.],
       [-1.,  0.,  1.],
       [ 1., -0., -1.]])

In [76]:
x = np.random.rand(10) #包含10个随机数的数组

In [77]:
x

array([0.18687571, 0.70153492, 0.60534873, 0.66171297, 0.43338495,
       0.06107781, 0.63260489, 0.58361555, 0.72885336, 0.04941685])

In [78]:
x = x*10

In [79]:
x

array([1.86875711, 7.01534916, 6.05348731, 6.61712968, 4.33384951,
       0.6107781 , 6.32604886, 5.83615553, 7.28853365, 0.49416851])

In [80]:
np.floor(x) #所有元素向下取整

array([1., 7., 6., 6., 4., 0., 6., 5., 7., 0.])

In [81]:
np.ceil(x) #所有元素向上取整

array([2., 8., 7., 7., 5., 1., 7., 6., 8., 1.])

## 8.对矩阵不同维度上的元素进行计算

In [82]:
x = np.arange(0,10).reshape(2,5) #创建二维数组

In [83]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
np.sum(x) #二维数组所有元素求和

45

In [85]:
np.sum(x,axis=0) #二维数组纵向求和

array([ 5,  7,  9, 11, 13])

In [86]:
np.sum(x,axis=1) #二维数组横向求和

array([10, 35])

In [87]:
np.mean(x,axis=0) #二维数组纵向计算算术平均值

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [88]:
weight = [0.3,0.7] #权重

In [89]:
#二维数组纵向计算加权平均值
np.average(x,axis=0,weights=weight) #0.3与x的上面一行存，0.7与x的下面一行存，最后加起来得到答案

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [90]:
np.max(x) #所有元素的最大值

9

In [91]:
np.max(x,axis=0) #每列元素的最大值

array([5, 6, 7, 8, 9])

In [92]:
x = np.random.randint(0,10,size=(3,3)) #创建二维数组，randint生成一个指定范围内的整数

In [93]:
x

array([[4, 7, 3],
       [5, 7, 1],
       [7, 7, 6]])

In [94]:
np.std(x) #所有元素的标准差

2.042752923427804

In [95]:
np.std(x,axis=1) #每行元素的标准差

array([1.69967317, 2.49443826, 0.47140452])

In [96]:
np.std(x,axis=0) #每列元素的标准差

array([1.24721913, 0.        , 2.05480467])

In [97]:
np.sort(x,axis=0) #纵向排序

array([[4, 7, 1],
       [5, 7, 3],
       [7, 7, 6]])

In [98]:
np.sort(x,axis=1) #横向排序

array([[3, 4, 7],
       [1, 5, 7],
       [6, 7, 7]])

## 9.改变数组大小

In [99]:
a = np.arange(1,11,1)

In [100]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
a.shape=(2,5)

In [102]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [103]:
a.shape=(5,-1) #-1表示自动计算

In [104]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [105]:
b = a.reshape(2,5) #reshape方法返回一个新数组，不改变原来的那个数组

In [106]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## 10.切片操作

In [107]:
a = np.arange(10)

In [108]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [110]:
a[::2] #隔一个取一个元素

array([0, 2, 4, 6, 8])

In [111]:
a[:5] #前5个元素

array([0, 1, 2, 3, 4])

In [112]:
c = np.arange(25)

In [113]:
c.shape=(5,5)

In [114]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [115]:
c[0,2:5] #在0行中，下标[2,5)之间的元素值

array([2, 3, 4])

In [116]:
c[1] #第0行的所有元素

array([5, 6, 7, 8, 9])

In [117]:
c[2:5,2:5] #行下标和列下标都介于[2,5)之间的元素值

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

## 11.布尔运算

In [118]:
x = np.random.rand(10) #包含10个随机数的数组(0-1之间)

In [119]:
x

array([0.63674739, 0.33445022, 0.67576599, 0.93972875, 0.42967207,
       0.01543748, 0.13362567, 0.19972377, 0.35572127, 0.45366528])

In [120]:
x>0.5

array([ True, False,  True,  True, False, False, False, False, False,
       False])

In [121]:
x[x>0.5]

array([0.63674739, 0.67576599, 0.93972875])

In [122]:
a = np.array([1,2,3])

In [123]:
b = np.array([3,2,1])

In [124]:
a > b

array([False, False,  True])

In [125]:
a[a>b]

array([3])

In [126]:
a == b

array([False,  True, False])

In [127]:
a[a==b]

array([2])

## 12.广播

In [128]:
a = np.arange(0,60,10).reshape(-1,1) #列向量

In [129]:
b = np.arange(0,6) #行向量

In [130]:
a

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [131]:
b

array([0, 1, 2, 3, 4, 5])

In [132]:
a + b #广播

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [133]:
a * b

array([[  0,   0,   0,   0,   0,   0],
       [  0,  10,  20,  30,  40,  50],
       [  0,  20,  40,  60,  80, 100],
       [  0,  30,  60,  90, 120, 150],
       [  0,  40,  80, 120, 160, 200],
       [  0,  50, 100, 150, 200, 250]])

## 13.分段函数

In [134]:
x = np.random.randint(0,10,size=(1,10))

In [135]:
x

array([[0, 7, 2, 6, 6, 2, 1, 9, 3, 2]])

In [136]:
np.where(x<5,0,1)

array([[0, 1, 0, 1, 1, 0, 0, 1, 0, 0]])

In [137]:
#小于4的元素乘以2，大于7的元素乘以3，其他元素变为0
np.piecewise(x,[x<4,x>7],[lambda x:x*2,lambda x:x*3])

array([[ 0,  0,  4,  0,  0,  4,  2, 27,  6,  4]])

## 14.计算唯一值及出现的次数

In [138]:
x = np.random.randint(0,10,7)

In [139]:
x

array([3, 9, 6, 8, 0, 4, 7])

In [140]:
np.bincount(x) #元素出现的次数

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [141]:
np.sum(_)

7

In [142]:
len(x)

7

In [143]:
np.unique(x) #返回唯一元素值，有点类似于集合的意思

array([0, 3, 4, 6, 7, 8, 9])

In [144]:
x = np.random.randint(0,10,2) 

In [145]:
x

array([8, 5])

In [146]:
np.bincount(x) #数组长度取决于原始数组中最大元素值

array([0, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [147]:
x =np.random.randint(0,10,10)

In [148]:
x

array([3, 5, 7, 6, 5, 6, 6, 0, 8, 0])

In [149]:
y = np.random.rand(10) #随机小数，模拟权重

In [150]:
y

array([0.40357927, 0.14612307, 0.55450761, 0.03161557, 0.12193657,
       0.72967996, 0.87595106, 0.43600065, 0.65824781, 0.91190082])

In [151]:
y = np.round_(y,1) 

In [152]:
y

array([0.4, 0.1, 0.6, 0. , 0.1, 0.7, 0.9, 0.4, 0.7, 0.9])

In [153]:
np.sum(x*y)/np.sum(np.bincount(x)) #加权总和/出现总次数或者元素个数

2.16

In [154]:
np.sum(x*y)/len(x)

2.16

## 15.矩阵运算

In [155]:
a_list = [3,5,7]

In [156]:
a_mat = np.matrix(a_list) #创建矩阵

In [157]:
a_mat

matrix([[3, 5, 7]])

In [158]:
a_mat.T #矩阵转置

matrix([[3],
        [5],
        [7]])

In [159]:
a_mat.shape #矩阵形状

(1, 3)

In [160]:
a_mat.size

3

In [161]:
b_mat = np.matrix((1,2,3))

In [162]:
b_mat.shape

(1, 3)

In [163]:
a_mat * b_mat.T #矩阵相乘

matrix([[34]])

In [164]:
a_mat.mean() #元素平均值

5.0

In [165]:
a_mat.sum() #所有元素之和

15

In [166]:
a_mat.max()

7

In [167]:
c_mat = np.matrix(((1,5,3),(2,9,6))) #创建二维矩阵,创建的时候用列表或者用元组都可以

In [168]:
c_mat

matrix([[1, 5, 3],
        [2, 9, 6]])

In [169]:
c_mat.argsort(axis=0) #纵向排序后的元素序号

matrix([[0, 0, 0],
        [1, 1, 1]], dtype=int64)

In [170]:
c_mat.argsort(axis=1) #横向排序后的元素序号

matrix([[0, 2, 1],
        [0, 2, 1]], dtype=int64)

In [171]:
d_mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [172]:
d_mat.diagonal()

matrix([[1, 5, 9]])

In [173]:
d_mat.flatten() #矩阵平铺

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])