In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x<3

array([ True,  True, False, False, False])

In [4]:
x!=3

array([ True,  True, False,  True,  True])

In [5]:
(2*x)==(x**2)

array([False,  True, False, False, False])

# 1.和通用函数类似的比较操作
和算术运算符一样，比较运算操作在NumPy中也是借助通用函数实现的。

运算符 | 对应的通用函数
-|-
== | np.equal
!= | np.not_equal
< | np.less
<= | np.less_equal
\> | np.greater
\>= | np.greater_equal

In [6]:
rng = np.random.RandomState(0)
x = rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [7]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

# 2.操作布尔数组

In [8]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [9]:
#有多少值小于6
np.count_nonzero(x<6)

8

In [10]:
#在这个例子中，False会被解释成0，True会被解释成1
np.sum(x<6)

8

In [11]:
np.sum(x<6,axis=1) #每一行有多少个数字小于6

array([4, 2, 2])

如果要快速检查任意或者所有这些值是否为True，可以用np.any()或者np.all()

In [12]:
np.any(x>8)

True

In [13]:
np.any(x<0)

False

In [14]:
np.all(x<10)

True

In [15]:
np.all(x==6)

False

In [16]:
#是否每一行元素的值都小于8
np.all(x<8,axis=1)

array([ True, False,  True])

# 3.将布尔数组作为掩码

In [17]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [18]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [19]:
#现在为了将这些值从数组中选出，可以进行简单的索引，即掩码操作
#所有的这些值就是掩码数组对应位置为True的值
x[x<5]

array([0, 3, 3, 3, 2, 4])