# 1.数组值求和

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

48.059155070767815

In [3]:
np.sum(L)

48.0591550707678

因为NumPy的sum函数在编译码中执行操作，所以NumPy的操作更加快一些<br>
np.sum函数和sum函数并不等同，尤其是他们的可选参数都有不同的含义，np.sum函数是知道数组的维度的

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

157 ms ± 2.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.73 ms ± 35.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# 2.最小值和最大值

In [5]:
min(big_array),max(big_array)

(1.426291320605344e-07, 0.9999994498358663)

In [6]:
np.min(big_array),np.max(big_array) #NumPy也有类似的语法，并且执行的更快

(1.426291320605344e-07, 0.9999994498358663)

对于min、max、sum和其他NumPy聚合，一种更加简洁的语法形式是数组对象直接调用这些方法

In [7]:
print(big_array.max(),big_array.min())

0.9999994498358663 1.426291320605344e-07


## 多维度聚合
一种常用的聚合操作是沿着一行或一列聚合。<br>
**axis关键字指定的是数组将会被折叠的维度，而不是将要被返回的维度。因此指定axis=0意味着第一个轴将要被折叠，对于二维数组，这意味着每一列的值都将被聚合。**

函数名称 | 描述
-|-
np.sum | 计算元素的和
np.prod | 计算元素的积
np.mean | 计算元素的平均值
np.std | 计算元素的标准差
np.var | 计算元素的方差
np.min | 找出最小值
np.max | 找出最大值
np.argmin | 找出最小值的索引
np.argmax | 找出最大值的索引
np.median | 找出元素的中位数
np.percentile | 计算基于元素排序的统计值
np.any | 验证任何一个元素是否为真
np.all | 验证所有元素是否为真

In [8]:
M = np.random.random((3,4))
print(M)

[[0.00984746 0.57984648 0.24688568 0.84586624]
 [0.1143164  0.38253565 0.16809398 0.94402318]
 [0.24668247 0.75317947 0.73557489 0.06596923]]


In [9]:
M.sum()

5.0928211232781955

In [10]:
#返回每一列的最小值
M.min(axis=0)

array([0.00984746, 0.38253565, 0.16809398, 0.06596923])

In [11]:
#返回每一行的最大值
M.max(axis=1)

array([0.84586624, 0.94402318, 0.75317947])